# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bulker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.TextField(unique=True)),
                ('y', models.TextField()),
            ],
        ),
    ]
